name: Build Typst document
on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Fontist
        uses: fontist/setup-fontist@v2

      - name: Install Poppins
        run: fontist install "Poppins"
        
      - name: Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: |
            geschaeftsordnung.typ
            wahlordnung.typ

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: "*.pdf"

      - name: Upload to BayStuRa Webserver via SCP
        # if: github.ref_type == 'tag'
        # Install sshpass, then use it to upload the PDF files via SCP
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass
          sshpass -p ${{ secrets.SFTP_PASSWORD }} scp -P ${{ secrets.SFTP_PORT }} *.pdf ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_SERVER }}:${{ secrets.SFTP_DIRECTORY }}
        env:
          SFTP_SERVER: ${{ secrets.SFTP_SERVER }}
          SFTP_PORT: ${{ secrets.SFTP_PORT }}
          SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
          SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          name: "${{ github.repository }} — ${{ github.ref_name }}"
          files: "*.pdf"
