name: Build Typst document
on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        uses: fontist/setup-fontist@v2

      - name: Set up Fontist
        run: fontist install "Poppins"
        
      - name: Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: |
            geschaeftsordnung.typ
            wahlordnung.typ

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: "*.pdf"

      - name: Upload to BayStuRa Webserver via SFTP
        uses: appleboy/scp-action@v0.1.7
        if: github.ref_type == 'tag'
        with:
          host: ${{ secrets.SFTP_SERVER }}
          port: ${{ secrets.SFTP_PORT }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          source: "*.pdf"
          target: ${{ secrets.SFTP_DIRECTORY }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          name: "${{ github.repository }} — ${{ github.ref_name }}"
          files: "*.pdf"
